dropbox-sdk-dotnet/Examples/SimpleBlogDemo/Controllers/BlogsController.cs
using Dropbox.Api;
using SimpleBlogDemo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using SimpleBlogDemo.Helpers;
using System.Threading.Tasks;
using WebMatrix.WebData;

namespace SimpleBlogDemo.Controllers
{
    [RequireHttpsOrXForwarded]
    public partial class BlogsController : AsyncController
    {
        // GET: Blogs
        public async Task<ActionResult> DisplayAsync(string blogname, string id = null)
        {
            var user = this.GetBlogUser(blogname);
            if (user == null)
            {
                return RedirectToAction("Index", "Home");
            }

            using (var client = this.GetClient(user))
            {
                if (client == null)
                {
                    return RedirectToAction("Index", "Home");
                }

                var articles = new List<ArticleMetadata>(await client.GetArticleList());
                bool isEditable = WebSecurity.IsAuthenticated && WebSecurity.CurrentUserId == user.ID;

                Article article = null;

                if (!string.IsNullOrWhiteSpace(id))
                {
                    var filtered = from a in articles
                                   where a.DisplayName == id
                                   select a;
                    var selected = filtered.FirstOrDefault();
                    if (selected != null)
                    {
                        article = await client.GetArticle(blogname, selected);
                    }
                }

                if (article == null)
                {
                    return View("Index", Tuple.Create(articles, blogname, isEditable));
                }
                else
                {
                    return View("Display", Tuple.Create(article, articles, blogname, isEditable));
                }
           }
        }
    }

    public partial class BlogsController
    {
        private UsersStore store = new UsersStore();

        private UserProfile GetBlogUser(string blogname)
        {
            if (string.IsNullOrWhiteSpace(blogname))
            {
                return null;
            }

            var users = from u in store.Users
                        where u.BlogName == blogname
                        select u;

            return users.FirstOrDefault();
        }

        private DropboxClient GetClient(UserProfile user)
        {
            if (user == null || string.IsNullOrWhiteSpace(user.DropboxAccessToken))
            {
                return null;
            }

            return new DropboxClient(user.DropboxAccessToken, new DropboxClientConfig("SimpleBlogDemo"));
        }
    }
}

dropbox-sdk-dotnet/Examples/SimpleBlogDemo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;

using SimpleBlogDemo.Helpers;
using System.Globalization;
using SimpleBlogDemo.Models;
using System.Web.Configuration;
using System.Threading.Tasks;
using System.Net.Http;
using System.Web.Script.Serialization;
using Dropbox.Api;

namespace SimpleBlogDemo.Controllers
{
    [RequireHttpsOrXForwarded]
    public partial class HomeController : AsyncController
    {
        private UsersStore store = new UsersStore();
        private UserProfile currentUser;

        private string RedirectUri
        {
            get
            {
                if (this.Request.Url.Host.ToLowerInvariant() == "localhost")
                {
                    return string.Format("http://{0}:{1}/Home/Auth", this.Request.Url.Host, this.Request.Url.Port);
                }

                var builder = new UriBuilder(
                    Uri.UriSchemeHttps,
                    this.Request.Url.Host);

                builder.Path = "/Home/Auth";

                return builder.ToString();
            }
        }

        protected override void Initialize(System.Web.Routing.RequestContext requestContext)
        {
            this.currentUser = this.store.CurrentUser();

            base.Initialize(requestContext);
        }

        // GET: /Home
        public async Task<ActionResult> IndexAsync()
        {
            if (WebSecurity.IsAuthenticated)
            {
                return this.RedirectToAction("Profile");
            }

            var blogs = new List<Blog>();

            foreach (var user in store.Users)
            {
                var blog = await Blog.FromUserAsync(user);

                if (blog != null)
                {
                    blogs.Add(blog);
                }
            }

            blogs.Sort((l, r) => r.MostRecent.CompareTo(l.MostRecent));

            return View(blogs);
        }

        // GET: /Home/Register
        public ActionResult Register()
        {
            if (WebSecurity.IsAuthenticated)
            {
                return this.RedirectToAction("Profile");
            }

            return View();
        }

        // POST: /Home/Register
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Register(string username, string password1, string password2, string blogname, bool remember = false)
        {
            if (string.IsNullOrWhiteSpace(username))
            {
                this.Flash("Username must not be empty.", FlashLevel.Warning);
            }
            else if (string.IsNullOrWhiteSpace(password1) ||
                string.IsNullOrWhiteSpace(password2) ||
                !string.Equals(password1, password2, StringComparison.Ordinal))
            {
                this.Flash("Password must not be empty and both passwords must match.", FlashLevel.Warning);
            }
            else if (WebSecurity.UserExists(username))
            {
                this.Flash(string.Format(
                    CultureInfo.InvariantCulture,
                    "Username '{0}' already exists, choose something else.",
                    username),
                    FlashLevel.Warning);
            }
            else
            {
                var parameters = new Dictionary<string, object>();
                if (!string.IsNullOrEmpty(blogname))
                {
                    parameters["BlogName"] = blogname;
                }
                WebSecurity.CreateUserAndAccount(username, password1, parameters, requireConfirmationToken: false);
                WebSecurity.Login(username, password1, persistCookie: remember);
                return this.RedirectToAction("Profile");
            }

            return View();
        }

        // Get /Home/Profile
        [Authorize]
        public async Task<ActionResult> ProfileAsync()
        {
            await Task.Delay(0);

            return View(this.currentUser);
        }

        // Post /Home/Profile
        [HttpPost, ValidateAntiForgeryToken, Authorize]
        public async Task<ActionResult> ProfileAsync(UserProfile profile)
        {
            if (this.currentUser.ID != profile.ID)
            {
                return this.RedirectToAction("Index");
            }

            this.currentUser.BlogName = profile.BlogName;
            await this.store.SaveChangesAsync();

            return View(this.currentUser);
        }

        // POST : /Home/Disconnect
        [HttpPost, ValidateAntiForgeryToken, Authorize]
        public async Task<ActionResult> DisconnectAsync()
        {
            if (!string.IsNullOrWhiteSpace(this.currentUser.BlogName))
            {
                this.FlushCache(this.currentUser.BlogName);
            }

            this.currentUser.DropboxAccessToken = string.Empty;
            await store.SaveChangesAsync();

            this.Flash("This account has been disconnected from Dropbox.", FlashLevel.Success);
            return this.RedirectToAction("Profile");
        }

        // GET: /Home/Connect
        [Authorize]
        public ActionResult Connect()
        {
            if (!string.IsNullOrWhiteSpace(this.currentUser.DropboxAccessToken))
            {
                return this.RedirectToAction("Index");
            }

            this.currentUser.ConnectState = Guid.NewGuid().ToString("N");
            store.SaveChanges();

            var redirect = DropboxOAuth2Helper.GetAuthorizeUri(
                OAuthResponseType.Code,
                MvcApplication.AppKey,
                RedirectUri,
                this.currentUser.ConnectState);

            return Redirect(redirect.ToString());
        }

        // GET: /Home/Auth
        [Authorize]
        public async Task<ActionResult> AuthAsync(string code, string state)
        {
            try
            {
                if (this.currentUser.ConnectState != state)
                {
                    this.Flash("There was an error connecting to Dropbox.");
                    return this.RedirectToAction("Index");
                }

                var response = await DropboxOAuth2Helper.ProcessCodeFlowAsync(
                    code,
                    MvcApplication.AppKey,
                    MvcApplication.AppSecret,
                    this.RedirectUri);

                this.currentUser.DropboxAccessToken = response.AccessToken;
                this.currentUser.ConnectState = string.Empty;
                await this.store.SaveChangesAsync();

                this.Flash("This account has been connected to Dropbox.", FlashLevel.Success);
                return RedirectToAction("Profile");
            }
            catch(Exception e)
            {
                var message = string.Format(
                    "code: {0}\nAppKey: {1}\nAppSecret: {2}\nRedirectUri: {3}\nException : {4}",
                    code,
                    MvcApplication.AppKey,
                    MvcApplication.AppSecret,
                    this.RedirectUri,
                    e);
                this.Flash(message, FlashLevel.Danger);
                return RedirectToAction("Profile");
            }
        }

        // POST: /Home/LogOff
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult LogOff()
        {
            if (WebSecurity.IsAuthenticated)
            {
                WebSecurity.Logout();
            }

            return RedirectToAction("Index");
        }

        // GET: /Home/SignIn
        public ActionResult SignIn(string returnUrl=null)
        {
            if (WebSecurity.IsAuthenticated)
            {
                if (!string.IsNullOrEmpty(returnUrl))
                {
                    return Redirect(returnUrl);
                }
                else
                {
                    return RedirectToAction("Profile");
                }
            }

            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult SignIn(string username, string password, string returnUrl = null, bool remember = false)
        {
            if (string.IsNullOrWhiteSpace(username) || string.IsNullOrWhiteSpace(password))
            {
                this.Flash("Incorrect username or password.", FlashLevel.Danger);
                ViewBag.ReturnUrl = returnUrl;
                return View();
            }

            if (!WebSecurity.IsAuthenticated)
            {
                var result = WebSecurity.Login(username, password, persistCookie: remember);
                if (!result)
                {
                    this.Flash("Incorrect username or password.", FlashLevel.Warning);
                    ViewBag.ReturnUrl = returnUrl;
                    return View();
                }
                else if (remember)
                {
                    Response.Cookies.Get(".ASPXAUTH").Expires = DateTime.UtcNow.AddDays(30);
                }
           }

            if (!string.IsNullOrEmpty(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction("Profile");
            }
        }
    }
}

dropbox-sdk-dotnet/Examples/SimpleBlogDemo/Views/Home/Index.cshtml
@model List<Blog>
@{
    ViewBag.Title = "Home";
}

<div class="text-center jumbotron margin-top-20">
    <h1>Welcome to the Simple Blog Demo</h1>
    <h2>
        This is a sample application that demonstrates how to use the <a href="https://www.dropbox.com">Dropbox</a>
        .Net SDK to build a simple blog.
    </h2>

    @Html.ActionLink(
        linkText: "Sign up now!",
        actionName: "Register",
        routeValues: new {},
        htmlAttributes: new { @class = "btn btn-lg btn-primary" })
</div>

<div class="row">
    @foreach (var blog in Model)
    {
        <div class="col-md-3 well">
            <h4>@blog.BlogName</h4>
            <ul>
                @foreach (var article in blog.BlogArticles.Reverse().Take(5))
                {
                    <li><a href="/Blogs/@blog.BlogName/@article.DisplayName">@article.Name</a></li>
                }
            </ul>
        </div>
    }
</div>

dropbox-sdk-dotnet/Examples/SimpleBlogDemo/Views/Home/Profile.cshtml
@model SimpleBlogDemo.Models.UserProfile

@{
    ViewBag.Title = "Profile";
}

<h2>Profile</h2>

<div class="row">
    <div class="well col-md-offset-3 col-md-6">
        @using (@Html.BeginForm("Profile", "Home", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, string.Empty, new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID);
            @Html.HiddenFor(model => model.UserName);

            <div class="form-group">
                <label class="control-label">
                    Username
                </label>
                <div class="form-control">
                    @Model.UserName
                </div>
            </div>

            <div class="form-group">
                <label class="control-label">
                    Password
                </label>
                <div class="form-control">
                    &bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;
                </div>
            </div>

            <div class="form-group">
                @if (string.IsNullOrWhiteSpace(Model.BlogName))
                {
                    @Html.LabelFor(model => model.BlogName, new { @class = "control-label" })
                    <div>
                        @Html.EditorFor(model => model.BlogName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.BlogName, string.Empty, new { @class = "text-danger" })
                    </div>
                }
                else
                {
                    <label class="control-label">
                        Blog Name
                    </label>
                    <div class="form-control">
                        @Html.ActionLink(@Model.BlogName, @Model.BlogName, "Blogs")
                    </div>
                }
            </div>

            <div class="form-group">
                <label class="control-label">
                    Dropbox Connection
                </label>
                <div>
                    @if (string.IsNullOrWhiteSpace(Model.DropboxAccessToken))
                    {
                        @Html.ActionLink(
                                    linkText: "connect",
                                    actionName: "Connect",
                                    routeValues: null,
                                    htmlAttributes: new { @class = "btn btn-sm btn-default" })
                    }
                    else
                    {
                        <input type="submit" class="btn btn-sm btn-default" value="disconnect"
                               form="disconnect-form" />
                    }
                </div>
            </div>

            if (string.IsNullOrWhiteSpace(Model.BlogName))
            {
                <div class="form-group text-center">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            }
        }
        @using (Html.BeginForm("Disconnect", "Home", FormMethod.Post, new { id = "disconnect-form" }))
        {
            @Html.AntiForgeryToken();
        }
    </div>
</div>

dropbox-sdk-dotnet/Examples/SimpleBlogDemo/Views/Home/Register.cshtml
@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>

<div class="well col-md-offset-3 col-md-6">
@using (Html.BeginForm(actionName: "Register", controllerName: "Home", method:FormMethod.Post))
{
    @Html.AntiForgeryToken();
    
    <div class="form-group">
        @Html.Label("Username", htmlAttributes: new { @class = "control-label", @for = "username" })
        @Html.TextBox("username", null, htmlAttributes: new { @class = "form-control", placeholder="username (email)" })
    </div>
    
    <div class="form-group">
        @Html.Label("Password", htmlAttributes: new { @class = "control-label", @for = "password1" })
        @Html.Password("password1", null, htmlAttributes: new { @class = "form-control" })
    </div>
    
    <div class="form-group">
        @Html.Label("Repeat Password", htmlAttributes: new { @class = "control-label", @for = "password2" })
        @Html.Password("password2", null, htmlAttributes: new { @class = "form-control" })
    </div>
    
    <div class="form-group">
        @Html.Label("Blog Name (optional)", htmlAttributes: new { @class = "control-label", @for = "blogname" })
        @Html.TextBox("blogname", null, htmlAttributes: new { @class = "form-control" })
    </div>
    
    <div class="checkbox">
        <label>
            Remember me
            <input type="checkbox" id="remember" name="remember" value="true"/>
        </label>
    </div>
    
    <div class="form-group">
        <input type="submit" value="Register" class="btn btn-primary" />
    </div>
}
</div>

dropbox-sdk-dotnet/Examples/SimpleBlogDemo/Views/Home/SignIn.cshtml
@{
    ViewBag.Title = "Sign In";
}

<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <h2>Sign In</h2>

        <div class="well">
            @using (Html.BeginForm("SignIn", "Home", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.Hidden("returnUrl", (string)ViewBag.ReturnUrl);

                <div class="form-group">
                    @Html.Label("Username", htmlAttributes: new { @class = "control-label", @for = "username" })
                    @Html.TextBox("username", null, htmlAttributes: new { @class = "form-control", placeholder = "username (email)" })
                </div>

                <div class="form-group">
                    @Html.Label("Password", htmlAttributes: new { @class = "control-label", @for = "password" })
                    @Html.Password("password", null, htmlAttributes: new { @class = "form-control" })
                </div>

                <div class="checkbox">
                    <label>
                        Remember me
                        <input type="checkbox" id="remember" name="remember" value="true"/>
                        <hidden name="remember" value="false" />
                    </label>
                </div>

                <div class="form-group">
                    <input type="submit" value="Sign In" class="btn btn-primary" />
                </div>
            }
        </div>
    </div>
</div>