dropbox-sdk-dotnet/Examples/SimpleBlogDemo/Controllers/BlogsController.cs
using Dropbox.Api;
using SimpleBlogDemo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using SimpleBlogDemo.Helpers;
using System.Threading.Tasks;
using WebMatrix.WebData;

namespace SimpleBlogDemo.Controllers
{
    [RequireHttpsOrXForwarded]
    public partial class BlogsController : AsyncController
    {
        // GET: Blogs
        public async Task<ActionResult> DisplayAsync(string blogname, string id = null)
        {
            var user = this.GetBlogUser(blogname);
            if (user == null)
            {
                return RedirectToAction("Index", "Home");
            }

            using (var client = this.GetClient(user))
            {
                if (client == null)
                {
                    return RedirectToAction("Index", "Home");
                }

                var articles = new List<ArticleMetadata>(await client.GetArticleList());
                bool isEditable = WebSecurity.IsAuthenticated && WebSecurity.CurrentUserId == user.ID;

                Article article = null;

                if (!string.IsNullOrWhiteSpace(id))
                {
                    var filtered = from a in articles
                                   where a.DisplayName == id
                                   select a;
                    var selected = filtered.FirstOrDefault();
                    if (selected != null)
                    {
                        article = await client.GetArticle(blogname, selected);
                    }
                }

                if (article == null)
                {
                    return View("Index", Tuple.Create(articles, blogname, isEditable));
                }
                else
                {
                    return View("Display", Tuple.Create(article, articles, blogname, isEditable));
                }
           }
        }
    }

    public partial class BlogsController
    {
        private UsersStore store = new UsersStore();

        private UserProfile GetBlogUser(string blogname)
        {
            if (string.IsNullOrWhiteSpace(blogname))
            {
                return null;
            }

            var users = from u in store.Users
                        where u.BlogName == blogname
                        select u;

            return users.FirstOrDefault();
        }

        private DropboxClient GetClient(UserProfile user)
        {
            if (user == null || string.IsNullOrWhiteSpace(user.DropboxAccessToken))
            {
                return null;
            }

            return new DropboxClient(user.DropboxAccessToken, new DropboxClientConfig("SimpleBlogDemo"));
        }
    }
}

dropbox-sdk-dotnet/Examples/SimpleBlogDemo/Controllers/EditController.cs
namespace SimpleBlogDemo.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;

    using SimpleBlogDemo.Helpers;
    using SimpleBlogDemo.Models;
    using System.IO;
    using System.Text;
    using Dropbox.Api.Files;
    using Dropbox.Api;
    using System;
    using System.Globalization;
    using System.Web;

    [Authorize, RequireHttpsOrXForwarded]
    public class EditController : AsyncController
    {
        private UsersStore store = new UsersStore();
        private UserProfile currentUser;

        protected override void Initialize(System.Web.Routing.RequestContext requestContext)
        {
            this.currentUser = this.store.CurrentUser();

            base.Initialize(requestContext);
        }

        // GET: Edit/{id}
        public async Task<ActionResult> IndexAsync(string id)
        {
            using (var client = this.currentUser.GetAuthenticatedClient())
            {
                if (client == null)
                {
                    return RedirectToAction("Profile", "Home");
                }

                var articles = await client.GetArticleList();
                var filtered = from a in articles
                               where a.DisplayName == id
                               select a;
                var selected = filtered.FirstOrDefault();
                if (selected == null)
                {
                    return RedirectToAction("Display", "Blogs", new { blogname = this.currentUser.BlogName });
                }

                using (var download = await client.Files.DownloadAsync("/" + selected.Filename))
                {
                    var markdown = await download.GetContentAsStringAsync();

                    return View(Tuple.Create(markdown, selected));
                }
            }
        }

        // POST: /Edit
        [HttpPost, ValidateAntiForgeryToken, ValidateInput(enableValidation: false)]
        public async Task<ActionResult> IndexAsync(
            string filename,
            string content,
            string rev)
        {
            using (var client = this.currentUser.GetAuthenticatedClient())
            {
                if (client == null)
                {
                    return RedirectToAction("Profile", "Home");
                }

                using (var mem = new MemoryStream(Encoding.UTF8.GetBytes(content)))
                {
                    try
                    {
                        var updated = await client.Files.UploadAsync(
                            "/" + filename,
                            WriteMode.Overwrite.Instance,
                            body: mem);
                        rev = updated.Rev;
                    }
                    catch (ApiException<UploadError> e)
                    {
                        var uploadError = e.ErrorResponse.AsPath;
                        if (uploadError != null)
                        {
                            var reason = uploadError.Value.Reason;
                            var id = filename.Split('.')[0];

                            var message = string.Format( "Unable to update {0}. Reason: {1}", id, reason);

                            this.Flash(message, FlashLevel.Warning);
                            return RedirectToAction("Index", new { id = id });
                        }
                    }
                }

                var metadata = ArticleMetadata.Parse(filename, rev);

                await client.GetArticle(this.currentUser.BlogName, metadata, bypassCache: true);

                this.Flash(string.Format(
                    "Updated '{0}'.", metadata.Name));
                return Redirect(string.Format(
                    "/Blogs/{0}/{1}",
                    this.currentUser.BlogName,
                    metadata.DisplayName));
            }
        }

        // GET: /Add
        public ActionResult Add()
        {
            return View();
        }

        // POST: /Add
        [HttpPost, ValidateAntiForgeryToken, ValidateInput(enableValidation: false)]
        public async Task<ActionResult> AddAsync(string name, DateTime date, string content)
        {
            var filename = string.Format(
                CultureInfo.InvariantCulture,
                "{0}.{1:yyyyMMdd}.md",
                name,
                date);

            using (var client = this.currentUser.GetAuthenticatedClient())
            {
                if (client == null)
                {
                    return RedirectToAction("Profile", "Home");
                }

                using (var mem = new MemoryStream(Encoding.UTF8.GetBytes(content)))
                {
                    var upload = await client.Files.UploadAsync("/" + filename, body: mem);

                    var metadata = ArticleMetadata.Parse(upload.Name, upload.Rev);

                    return Redirect(string.Format(
                        CultureInfo.InvariantCulture,
                        "/Blogs/{0}/{1}",
                        this.currentUser.BlogName,
                        metadata.DisplayName));
                }
            }
        }

        // POST: /Preview
        // This is called by an ajax request in preview.js
        [HttpPost, ValidateAntiForgeryToken, ValidateInput(enableValidation: false)]
        public ActionResult Preview(string markdown)
        {
            return Content(markdown.ParseMarkdown().ToString());
        }
    }
}

dropbox-sdk-dotnet/Examples/SimpleBlogDemo/Views/Blogs/Display.cshtml
@model Tuple<Article, List<ArticleMetadata>, string, bool>

@{
    var article = Model.Item1;
    var list = Model.Item2;
    var blogname = Model.Item3;
    var isEditable = Model.Item4;

    ViewBag.Title = article != null ? article.Metadata.Name : "Articles";
}

@article.Content

<div class="row">
    @for (var i = 0; i < list.Count; i++) 
    {
        var curr = list[i];
        if (curr.DisplayName == article.Metadata.DisplayName)
        {
            <div class="col-md-5 text-right">
                @if (i > 0)
                {
                    <a href="/Blogs/@blogname/@list[i-1].DisplayName">&laquo; @list[i-1].Name</a>
                }
            </div>
            <div class="col-md-2 text-center">
                |
                <a href="/Blogs/@blogname/">all</a>
                |
                @if (isEditable)
                {
                    @Html.ActionLink("edit", article.Metadata.DisplayName, "Edit")
                    @:|
                }
            </div>
            <div class="col-md-5 text-left">
                @if (i + 1 < list.Count)
                {
                    <a href="/Blogs/@blogname/@list[i+1].DisplayName">@list[i+1].Name &raquo;</a>
                }
            </div>
            break;
        }
    }
</div>

dropbox-sdk-dotnet/Examples/SimpleBlogDemo/Views/Blogs/Index.cshtml
@model Tuple<List<ArticleMetadata>, string, bool>

@{
    var list = Model.Item1;
    list.Reverse();
    var blogname = Model.Item2;
    var isEditable = Model.Item3;

    ViewBag.Title = blogname + " Articles";
}

<div class="row">
    <h2 class="col-md-offset-2 col-md-8">Articles</h2>
</div>

<div class="row">
    <div class="col-md-offset-2 col-md-6">
        <strong>Name</strong>
    </div>
    <div class="col-md-2">
        <strong>Date</strong>
    </div>
</div>

@foreach (var curr in list)
{
    <div class="row">
        <div class="col-md-offset-2 col-md-6">
            <a href="/Blogs/@blogname/@curr.DisplayName">@curr.Name</a>
            @if (isEditable)
            {
                <a href="/Edit/@curr.DisplayName">[edit]</a>
            }
        </div>
        <div class="col-md-2">
            @curr.Date.ToShortDateString()
        </div>
    </div>
}

@if (isEditable)
{
    <div class="row">
        <div class="col-md-offset-2 col-md-6">
            New Article
            <a href="/Add">[add]</a>
        </div>
    </div>
}